// Package api implements the HTTP transport layer for LedgerPro.
// This file implements RFC 7807 Problem Details for standardized error responses.
package api

import (
	"encoding/json"
	"net/http"
)

// ---------------------------------------------------------------------------
// RFC 7807 Problem Details (https://www.rfc-editor.org/rfc/rfc7807)
// ---------------------------------------------------------------------------

// ProblemDetail represents a structured error response per RFC 7807.
// Every error response from the API uses this format for consistency.
type ProblemDetail struct {
	// Type is a URI reference that identifies the problem type.
	Type string `json:"type"`

	// Title is a short, human-readable summary of the problem type.
	Title string `json:"title"`

	// Status is the HTTP status code generated by the origin server.
	Status int `json:"status"`

	// Detail is a human-readable explanation specific to this occurrence.
	Detail string `json:"detail"`

	// Instance is a URI reference that identifies the specific occurrence.
	Instance string `json:"instance,omitempty"`

	// TraceID is the distributed trace identifier for this request.
	TraceID string `json:"trace_id,omitempty"`

	// InvalidParams lists parameters that failed validation (RFC 9457 extension).
	InvalidParams []InvalidParam `json:"invalid_params,omitempty"`
}

// InvalidParam describes a single parameter that failed validation.
type InvalidParam struct {
	Name   string `json:"name"`
	Reason string `json:"reason"`
}

// ---------------------------------------------------------------------------
// Problem Type Constants
// ---------------------------------------------------------------------------

const (
	// Base URI for LedgerPro problem types
	problemBaseURI = "https://ledgerpro.dev/errors"

	// Domain errors
	ProblemTypeValidation        = problemBaseURI + "/validation-error"
	ProblemTypeBadRequest        = problemBaseURI + "/bad-request"
	ProblemTypeUnbalancedTx      = problemBaseURI + "/unbalanced-transaction"
	ProblemTypeDuplicateIdemKey  = problemBaseURI + "/duplicate-idempotency-key"
	ProblemTypeAccountNotFound   = problemBaseURI + "/account-not-found"
	ProblemTypeTxNotFound        = problemBaseURI + "/transaction-not-found"
	ProblemTypeLockFailed        = problemBaseURI + "/lock-acquisition-failed"
	ProblemTypeInternalError     = problemBaseURI + "/internal-error"
	ProblemTypeUnauthorized      = problemBaseURI + "/unauthorized"
	ProblemTypeForbidden         = problemBaseURI + "/forbidden"
	ProblemTypeRateLimitExceeded = problemBaseURI + "/rate-limit-exceeded"
	ProblemTypeInvalidCurrency   = problemBaseURI + "/invalid-currency"
	ProblemTypeServiceUnavail    = problemBaseURI + "/service-unavailable"
)

// ---------------------------------------------------------------------------
// Problem Constructors — Builder Pattern
// ---------------------------------------------------------------------------

// NewProblem creates a ProblemDetail with the given type, title, status, and detail.
func NewProblem(problemType, title string, status int, detail string) *ProblemDetail {
	return &ProblemDetail{
		Type:   problemType,
		Title:  title,
		Status: status,
		Detail: detail,
	}
}

// WithInstance sets the instance URI on the problem.
func (p *ProblemDetail) WithInstance(instance string) *ProblemDetail {
	p.Instance = instance
	return p
}

// WithTraceID sets the trace ID from the request context.
func (p *ProblemDetail) WithTraceID(traceID string) *ProblemDetail {
	p.TraceID = traceID
	return p
}

// WithInvalidParams attaches validation failure details.
func (p *ProblemDetail) WithInvalidParams(params ...InvalidParam) *ProblemDetail {
	p.InvalidParams = params
	return p
}

// ---------------------------------------------------------------------------
// Common Problem Factories
// ---------------------------------------------------------------------------

// BadRequest returns a 400 problem for malformed requests.
func BadRequest(detail string) *ProblemDetail {
	return NewProblem(ProblemTypeBadRequest, "Bad Request", http.StatusBadRequest, detail)
}

// ValidationError returns a 422 problem for validation failures.
func ValidationError(detail string, params ...InvalidParam) *ProblemDetail {
	return NewProblem(ProblemTypeValidation, "Validation Error", http.StatusUnprocessableEntity, detail).
		WithInvalidParams(params...)
}

// UnbalancedTransaction returns a 422 problem for debit/credit mismatch.
func UnbalancedTransaction(detail string, params ...InvalidParam) *ProblemDetail {
	return NewProblem(ProblemTypeUnbalancedTx, "Unbalanced Bookkeeping Entries", http.StatusUnprocessableEntity, detail).
		WithInvalidParams(params...)
}

// NotFound returns a 404 problem.
func NotFound(problemType, title, detail string) *ProblemDetail {
	return NewProblem(problemType, title, http.StatusNotFound, detail)
}

// AccountNotFound returns a 404 problem for missing accounts.
func AccountNotFound(detail string) *ProblemDetail {
	return NotFound(ProblemTypeAccountNotFound, "Account Not Found", detail)
}

// TransactionNotFound returns a 404 problem for missing transactions.
func TransactionNotFound(detail string) *ProblemDetail {
	return NotFound(ProblemTypeTxNotFound, "Transaction Not Found", detail)
}

// DuplicateIdempotencyKey returns a 409 problem for replayed idempotency keys.
func DuplicateIdempotencyKey(detail string) *ProblemDetail {
	return NewProblem(ProblemTypeDuplicateIdemKey, "Duplicate Idempotency Key", http.StatusConflict, detail)
}

// LockAcquisitionFailed returns a 503 problem when distributed lock cannot be obtained.
func LockAcquisitionFailed(detail string) *ProblemDetail {
	return NewProblem(ProblemTypeLockFailed, "Lock Acquisition Failed", http.StatusServiceUnavailable, detail)
}

// InternalError returns a 500 problem. The detail should NOT leak internals.
func InternalError(detail string) *ProblemDetail {
	return NewProblem(ProblemTypeInternalError, "Internal Server Error", http.StatusInternalServerError, detail)
}

// Unauthorized returns a 401 problem for missing/invalid authentication.
func Unauthorized(detail string) *ProblemDetail {
	return NewProblem(ProblemTypeUnauthorized, "Unauthorized", http.StatusUnauthorized, detail)
}

// Forbidden returns a 403 problem for insufficient permissions.
func Forbidden(detail string) *ProblemDetail {
	return NewProblem(ProblemTypeForbidden, "Forbidden", http.StatusForbidden, detail)
}

// RateLimitExceeded returns a 429 problem.
func RateLimitExceeded(detail string) *ProblemDetail {
	return NewProblem(ProblemTypeRateLimitExceeded, "Rate Limit Exceeded", http.StatusTooManyRequests, detail)
}

// ServiceUnavailable returns a 503 problem for degraded dependencies.
func ServiceUnavailable(detail string) *ProblemDetail {
	return NewProblem(ProblemTypeServiceUnavail, "Service Unavailable", http.StatusServiceUnavailable, detail)
}

// ---------------------------------------------------------------------------
// HTTP Response Writer
// ---------------------------------------------------------------------------

// WriteProblem serializes a ProblemDetail to the response writer with the
// correct Content-Type (application/problem+json) per RFC 7807.
func WriteProblem(w http.ResponseWriter, r *http.Request, problem *ProblemDetail) {
	if problem.TraceID == "" {
		problem.TraceID = GetTraceID(r.Context())
	}
	if problem.Instance == "" {
		problem.Instance = r.URL.Path
	}

	w.Header().Set("Content-Type", "application/problem+json; charset=utf-8")
	w.WriteHeader(problem.Status)
	_ = json.NewEncoder(w).Encode(problem)
}
