// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountType string

const (
	AccountTypeAsset     AccountType = "asset"
	AccountTypeLiability AccountType = "liability"
	AccountTypeEquity    AccountType = "equity"
	AccountTypeRevenue   AccountType = "revenue"
	AccountTypeExpense   AccountType = "expense"
)

func (e *AccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountType(s)
	case string:
		*e = AccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountType: %T", src)
	}
	return nil
}

type NullAccountType struct {
	AccountType AccountType `json:"account_type"`
	Valid       bool        `json:"valid"` // Valid is true if AccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountType), nil
}

type OutboxStatus string

const (
	OutboxStatusPending   OutboxStatus = "pending"
	OutboxStatusPublished OutboxStatus = "published"
	OutboxStatusFailed    OutboxStatus = "failed"
)

func (e *OutboxStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxStatus(s)
	case string:
		*e = OutboxStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxStatus: %T", src)
	}
	return nil
}

type NullOutboxStatus struct {
	OutboxStatus OutboxStatus `json:"outbox_status"`
	Valid        bool         `json:"valid"` // Valid is true if OutboxStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxStatus), nil
}

type PostingDirection string

const (
	PostingDirectionDebit  PostingDirection = "debit"
	PostingDirectionCredit PostingDirection = "credit"
)

func (e *PostingDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PostingDirection(s)
	case string:
		*e = PostingDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for PostingDirection: %T", src)
	}
	return nil
}

type NullPostingDirection struct {
	PostingDirection PostingDirection `json:"posting_direction"`
	Valid            bool             `json:"valid"` // Valid is true if PostingDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPostingDirection) Scan(value interface{}) error {
	if value == nil {
		ns.PostingDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PostingDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPostingDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PostingDirection), nil
}

// Chart of accounts — each row is a unique ledger account.
type Account struct {
	ID          int64       `json:"id"`
	AccountName string      `json:"account_name"`
	AccountType AccountType `json:"account_type"`
	// ISO 4217 currency code. Amounts are stored in smallest unit (e.g., paisa for INR).
	Currency  string             `json:"currency"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	TenantID  uuid.UUID          `json:"tenant_id"`
}

// Metadata for files (receipts/invoices) attached to transactions and stored in R2.
type Document struct {
	ID            uuid.UUID          `json:"id"`
	TransactionID uuid.UUID          `json:"transaction_id"`
	Filename      string             `json:"filename"`
	ContentType   string             `json:"content_type"`
	SizeBytes     int64              `json:"size_bytes"`
	ObjectKey     string             `json:"object_key"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	TenantID      uuid.UUID          `json:"tenant_id"`
}

// Transactional outbox for guaranteed event delivery. Written within the same ACID TX as ledger postings.
type LedgerOutbox struct {
	ID          uuid.UUID          `json:"id"`
	EventType   string             `json:"event_type"`
	RoutingKey  string             `json:"routing_key"`
	Payload     json.RawMessage    `json:"payload"`
	Status      OutboxStatus       `json:"status"`
	RetryCount  int32              `json:"retry_count"`
	MaxRetries  int32              `json:"max_retries"`
	LastError   pgtype.Text        `json:"last_error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	TenantID    uuid.UUID          `json:"tenant_id"`
}

// Individual debit/credit legs of a transaction. Append-only — never updated or deleted.
type Posting struct {
	ID            int64     `json:"id"`
	TransactionID uuid.UUID `json:"transaction_id"`
	AccountID     int64     `json:"account_id"`
	// Positive integer in smallest currency unit (e.g., paisa). Direction is expressed via the direction enum.
	Amount    int64              `json:"amount"`
	Direction PostingDirection   `json:"direction"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	TenantID  uuid.UUID          `json:"tenant_id"`
}

type Tenant struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// A financial transaction — groups one or more postings that must balance.
type Transaction struct {
	ID uuid.UUID `json:"id"`
	// Client-provided key to prevent duplicate transaction creation.
	IdempotencyKey string             `json:"idempotency_key"`
	Description    string             `json:"description"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	TenantID       uuid.UUID          `json:"tenant_id"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	TenantID     uuid.UUID          `json:"tenant_id"`
}
