// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAccounts = `-- name: CountAccounts :one
SELECT COUNT(*) FROM accounts
WHERE tenant_id = $1
`

func (q *Queries) CountAccounts(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAccounts, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactions = `-- name: CountTransactions :one
SELECT COUNT(*) FROM transactions
WHERE tenant_id = $1
`

func (q *Queries) CountTransactions(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactions, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one

INSERT INTO accounts (tenant_id, account_name, account_type, currency, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, account_name, account_type, currency, metadata, created_at, tenant_id
`

type CreateAccountParams struct {
	TenantID    uuid.UUID   `json:"tenant_id"`
	AccountName string      `json:"account_name"`
	AccountType AccountType `json:"account_type"`
	Currency    string      `json:"currency"`
	Metadata    []byte      `json:"metadata"`
}

// ---------------------------------------------------------------------------
// ACCOUNTS
// ---------------------------------------------------------------------------
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.TenantID,
		arg.AccountName,
		arg.AccountType,
		arg.Currency,
		arg.Metadata,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.AccountName,
		&i.AccountType,
		&i.Currency,
		&i.Metadata,
		&i.CreatedAt,
		&i.TenantID,
	)
	return i, err
}

const createDocument = `-- name: CreateDocument :one

INSERT INTO documents (tenant_id, transaction_id, filename, content_type, size_bytes, object_key)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, transaction_id, filename, content_type, size_bytes, object_key, created_at, tenant_id
`

type CreateDocumentParams struct {
	TenantID      uuid.UUID `json:"tenant_id"`
	TransactionID uuid.UUID `json:"transaction_id"`
	Filename      string    `json:"filename"`
	ContentType   string    `json:"content_type"`
	SizeBytes     int64     `json:"size_bytes"`
	ObjectKey     string    `json:"object_key"`
}

// ---------------------------------------------------------------------------
// DOCUMENTS (R2 Storage Attachments)
// ---------------------------------------------------------------------------
func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.TenantID,
		arg.TransactionID,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.ObjectKey,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.ObjectKey,
		&i.CreatedAt,
		&i.TenantID,
	)
	return i, err
}

const createOutboxEvent = `-- name: CreateOutboxEvent :one

INSERT INTO ledger_outbox (tenant_id, event_type, routing_key, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, event_type, routing_key, payload, status, retry_count, max_retries, last_error, created_at, processed_at, tenant_id
`

type CreateOutboxEventParams struct {
	TenantID   uuid.UUID       `json:"tenant_id"`
	EventType  string          `json:"event_type"`
	RoutingKey string          `json:"routing_key"`
	Payload    json.RawMessage `json:"payload"`
}

// ---------------------------------------------------------------------------
// OUTBOX (Transactional Event Delivery)
// ---------------------------------------------------------------------------
func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (LedgerOutbox, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent,
		arg.TenantID,
		arg.EventType,
		arg.RoutingKey,
		arg.Payload,
	)
	var i LedgerOutbox
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.RoutingKey,
		&i.Payload,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.LastError,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.TenantID,
	)
	return i, err
}

const createPosting = `-- name: CreatePosting :one

INSERT INTO postings (tenant_id, transaction_id, account_id, amount, direction)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, transaction_id, account_id, amount, direction, created_at, tenant_id
`

type CreatePostingParams struct {
	TenantID      uuid.UUID        `json:"tenant_id"`
	TransactionID uuid.UUID        `json:"transaction_id"`
	AccountID     int64            `json:"account_id"`
	Amount        int64            `json:"amount"`
	Direction     PostingDirection `json:"direction"`
}

// ---------------------------------------------------------------------------
// POSTINGS
// ---------------------------------------------------------------------------
func (q *Queries) CreatePosting(ctx context.Context, arg CreatePostingParams) (Posting, error) {
	row := q.db.QueryRow(ctx, createPosting,
		arg.TenantID,
		arg.TransactionID,
		arg.AccountID,
		arg.Amount,
		arg.Direction,
	)
	var i Posting
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.AccountID,
		&i.Amount,
		&i.Direction,
		&i.CreatedAt,
		&i.TenantID,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one


INSERT INTO tenants (name)
VALUES ($1)
RETURNING id, name, created_at
`

// ============================================================================
// LedgerPro: SQLC Queries
// ============================================================================
// ---------------------------------------------------------------------------
// TENANTS
// ---------------------------------------------------------------------------
func (q *Queries) CreateTenant(ctx context.Context, name string) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, name)
	var i Tenant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one

INSERT INTO transactions (tenant_id, idempotency_key, description, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, idempotency_key, description, metadata, created_at, tenant_id
`

type CreateTransactionParams struct {
	TenantID       uuid.UUID `json:"tenant_id"`
	IdempotencyKey string    `json:"idempotency_key"`
	Description    string    `json:"description"`
	Metadata       []byte    `json:"metadata"`
}

// ---------------------------------------------------------------------------
// TRANSACTIONS
// ---------------------------------------------------------------------------
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.TenantID,
		arg.IdempotencyKey,
		arg.Description,
		arg.Metadata,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
		&i.TenantID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (tenant_id, email, password_hash, role)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, role, created_at, updated_at, tenant_id
`

type CreateUserParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
}

// ---------------------------------------------------------------------------
// USERS
// ---------------------------------------------------------------------------
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const getAccountBalance = `-- name: GetAccountBalance :one

SELECT
    COALESCE(SUM(CASE WHEN direction = 'debit'  THEN amount ELSE 0 END), 0)::BIGINT AS total_debits,
    COALESCE(SUM(CASE WHEN direction = 'credit' THEN amount ELSE 0 END), 0)::BIGINT AS total_credits,
    (
        COALESCE(SUM(CASE WHEN direction = 'debit'  THEN amount ELSE 0 END), 0) -
        COALESCE(SUM(CASE WHEN direction = 'credit' THEN amount ELSE 0 END), 0)
    )::BIGINT AS net_balance
FROM postings
WHERE account_id = $1 AND tenant_id = $2
`

type GetAccountBalanceParams struct {
	AccountID int64     `json:"account_id"`
	TenantID  uuid.UUID `json:"tenant_id"`
}

type GetAccountBalanceRow struct {
	TotalDebits  int64 `json:"total_debits"`
	TotalCredits int64 `json:"total_credits"`
	NetBalance   int64 `json:"net_balance"`
}

// ---------------------------------------------------------------------------
// BALANCE COMPUTATION
// ---------------------------------------------------------------------------
func (q *Queries) GetAccountBalance(ctx context.Context, arg GetAccountBalanceParams) (GetAccountBalanceRow, error) {
	row := q.db.QueryRow(ctx, getAccountBalance, arg.AccountID, arg.TenantID)
	var i GetAccountBalanceRow
	err := row.Scan(&i.TotalDebits, &i.TotalCredits, &i.NetBalance)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, account_name, account_type, currency, metadata, created_at, tenant_id FROM accounts
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type GetAccountByIDParams struct {
	ID       int64     `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetAccountByID(ctx context.Context, arg GetAccountByIDParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, arg.ID, arg.TenantID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.AccountName,
		&i.AccountType,
		&i.Currency,
		&i.Metadata,
		&i.CreatedAt,
		&i.TenantID,
	)
	return i, err
}

const getAccountByName = `-- name: GetAccountByName :one
SELECT id, account_name, account_type, currency, metadata, created_at, tenant_id FROM accounts
WHERE account_name = $1 AND tenant_id = $2
LIMIT 1
`

type GetAccountByNameParams struct {
	AccountName string    `json:"account_name"`
	TenantID    uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetAccountByName(ctx context.Context, arg GetAccountByNameParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByName, arg.AccountName, arg.TenantID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.AccountName,
		&i.AccountType,
		&i.Currency,
		&i.Metadata,
		&i.CreatedAt,
		&i.TenantID,
	)
	return i, err
}

const getDocumentsByTransaction = `-- name: GetDocumentsByTransaction :many
SELECT id, transaction_id, filename, content_type, size_bytes, object_key, created_at, tenant_id FROM documents
WHERE transaction_id = $1 AND tenant_id = $2
ORDER BY created_at ASC
`

type GetDocumentsByTransactionParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	TenantID      uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetDocumentsByTransaction(ctx context.Context, arg GetDocumentsByTransactionParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, getDocumentsByTransaction, arg.TransactionID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.ObjectKey,
			&i.CreatedAt,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingOutboxEvents = `-- name: GetPendingOutboxEvents :many
SELECT id, event_type, routing_key, payload, status, retry_count, max_retries, last_error, created_at, processed_at, tenant_id FROM ledger_outbox
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1::INT
`

func (q *Queries) GetPendingOutboxEvents(ctx context.Context, batchSize int32) ([]LedgerOutbox, error) {
	rows, err := q.db.Query(ctx, getPendingOutboxEvents, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerOutbox{}
	for rows.Next() {
		var i LedgerOutbox
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.RoutingKey,
			&i.Payload,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.LastError,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostingsByAccountID = `-- name: GetPostingsByAccountID :many
SELECT
    p.id,
    p.tenant_id,
    p.transaction_id,
    t.description AS transaction_description,
    p.account_id,
    a.account_name,
    p.amount,
    p.direction,
    p.created_at
FROM postings p
JOIN accounts a ON a.id = p.account_id
JOIN transactions t ON t.id = p.transaction_id
WHERE p.account_id = $1 AND p.tenant_id = $2
ORDER BY p.created_at DESC
LIMIT $4::INT OFFSET $3::INT
`

type GetPostingsByAccountIDParams struct {
	AccountID  int64     `json:"account_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
	PageOffset int32     `json:"page_offset"`
	PageSize   int32     `json:"page_size"`
}

type GetPostingsByAccountIDRow struct {
	ID                     int64              `json:"id"`
	TenantID               uuid.UUID          `json:"tenant_id"`
	TransactionID          uuid.UUID          `json:"transaction_id"`
	TransactionDescription string             `json:"transaction_description"`
	AccountID              int64              `json:"account_id"`
	AccountName            string             `json:"account_name"`
	Amount                 int64              `json:"amount"`
	Direction              PostingDirection   `json:"direction"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetPostingsByAccountID(ctx context.Context, arg GetPostingsByAccountIDParams) ([]GetPostingsByAccountIDRow, error) {
	rows, err := q.db.Query(ctx, getPostingsByAccountID,
		arg.AccountID,
		arg.TenantID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPostingsByAccountIDRow{}
	for rows.Next() {
		var i GetPostingsByAccountIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TransactionID,
			&i.TransactionDescription,
			&i.AccountID,
			&i.AccountName,
			&i.Amount,
			&i.Direction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostingsByTransactionID = `-- name: GetPostingsByTransactionID :many
SELECT
    p.id,
    p.tenant_id,
    p.transaction_id,
    p.account_id,
    a.account_name,
    p.amount,
    p.direction,
    p.created_at
FROM postings p
JOIN accounts a ON a.id = p.account_id
WHERE p.transaction_id = $1 AND p.tenant_id = $2
ORDER BY p.id ASC
`

type GetPostingsByTransactionIDParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	TenantID      uuid.UUID `json:"tenant_id"`
}

type GetPostingsByTransactionIDRow struct {
	ID            int64              `json:"id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	TransactionID uuid.UUID          `json:"transaction_id"`
	AccountID     int64              `json:"account_id"`
	AccountName   string             `json:"account_name"`
	Amount        int64              `json:"amount"`
	Direction     PostingDirection   `json:"direction"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetPostingsByTransactionID(ctx context.Context, arg GetPostingsByTransactionIDParams) ([]GetPostingsByTransactionIDRow, error) {
	rows, err := q.db.Query(ctx, getPostingsByTransactionID, arg.TransactionID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPostingsByTransactionIDRow{}
	for rows.Next() {
		var i GetPostingsByTransactionIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TransactionID,
			&i.AccountID,
			&i.AccountName,
			&i.Amount,
			&i.Direction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, idempotency_key, description, metadata, created_at, tenant_id FROM transactions
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type GetTransactionByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, arg.ID, arg.TenantID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
		&i.TenantID,
	)
	return i, err
}

const getTransactionByIdempotencyKey = `-- name: GetTransactionByIdempotencyKey :one
SELECT id, idempotency_key, description, metadata, created_at, tenant_id FROM transactions
WHERE idempotency_key = $1 AND tenant_id = $2
LIMIT 1
`

type GetTransactionByIdempotencyKeyParams struct {
	IdempotencyKey string    `json:"idempotency_key"`
	TenantID       uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetTransactionByIdempotencyKey(ctx context.Context, arg GetTransactionByIdempotencyKeyParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByIdempotencyKey, arg.IdempotencyKey, arg.TenantID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
		&i.TenantID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, created_at, updated_at, tenant_id FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const incrementOutboxRetry = `-- name: IncrementOutboxRetry :exec
UPDATE ledger_outbox
SET retry_count = retry_count + 1, last_error = $2
WHERE id = $1 AND status = 'pending'
`

type IncrementOutboxRetryParams struct {
	ID        uuid.UUID   `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) IncrementOutboxRetry(ctx context.Context, arg IncrementOutboxRetryParams) error {
	_, err := q.db.Exec(ctx, incrementOutboxRetry, arg.ID, arg.LastError)
	return err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, account_name, account_type, currency, metadata, created_at, tenant_id FROM accounts
WHERE tenant_id = $1 AND id > $2::BIGINT
ORDER BY id ASC
LIMIT $3::INT
`

type ListAccountsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Cursor   int64     `json:"cursor"`
	PageSize int32     `json:"page_size"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts, arg.TenantID, arg.Cursor, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.AccountName,
			&i.AccountType,
			&i.Currency,
			&i.Metadata,
			&i.CreatedAt,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, idempotency_key, description, metadata, created_at, tenant_id FROM transactions
WHERE tenant_id = $1 AND created_at < $2::TIMESTAMPTZ
ORDER BY created_at DESC
LIMIT $3::INT
`

type ListTransactionsParams struct {
	TenantID        uuid.UUID          `json:"tenant_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	PageSize        int32              `json:"page_size"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions, arg.TenantID, arg.CursorCreatedAt, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :exec
UPDATE ledger_outbox
SET status = 'failed', last_error = $2, processed_at = now()
WHERE id = $1
`

type MarkOutboxEventFailedParams struct {
	ID        uuid.UUID   `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventFailed, arg.ID, arg.LastError)
	return err
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE ledger_outbox
SET status = 'published', processed_at = now()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}

const requeueFailedOutboxEvents = `-- name: RequeueFailedOutboxEvents :exec
UPDATE ledger_outbox
SET status = 'pending', retry_count = 0, last_error = '', processed_at = NULL
WHERE status = 'failed' AND retry_count < max_retries
`

func (q *Queries) RequeueFailedOutboxEvents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, requeueFailedOutboxEvents)
	return err
}
